---

- name: install the latest version of git
  yum: name=git state=latest

- name: get ius-release rpm
  get_url: url=http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-13.ius.centos6.noarch.rpm dest=/home/vagrant

- name: install ius-release repository rpm
  command: rpm --replacepkgs -Uvh /home/vagrant/ius-release-1.0-13.ius.centos6.noarch.rpm
  sudo: yes
