---

- name: ensure httpd and httpd tools are present
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel
    - httpd-tools
  sudo: yes
  tags:
    - webserver
    - httpd

- name: ensure httpd is running
  service: name=httpd state=running enabled=yes
  sudo: yes
  tags:
    - webserver
    - httpd

- name: configure docroot
  replace: dest=/etc/httpd/conf/httpd.conf regexp='^DocumentRoot.*' replace='DocumentRoot /vagrant_data'
  sudo: yes
  notify:
    - reload httpd
  tags:
    - webserver
    - httpd

- name: ensure virtual hosts config is present
  copy: src=nvh.conf dest=/etc/httpd/conf.d/nvh.conf mode=0644
  sudo: yes
  notify:
    - reload httpd
  tags:
    - webserver
    - httpd

- name: ensure php and modules are present
  yum: name={{ item }} state=present
  with_items:
    - php53u
    - php53u-pdo
    - php53u-mbstring
    - php53u-pecl-apc
    - php53u-devel
    - php53u-gd
    - php53u-soap
    - php53u-pear
    - php53u-pecl-imagick
    - php53u-cli
    - php53u-imap
    - php53u-xml
    - php53u-common
    - php53u-mcrypt
    - php53u-pecl-xdebug
    - php53u-process
  sudo: yes
  tags:
    - webserver
    - php


- name: Add php.ini
  copy: src=php.ini dest=/etc/php.ini mode=0644
  sudo: yes
  notify:
    - reload httpd
  tags:
    - webserver
    - php

- name: ensure xdebug.ini is present
  copy: src=xdebug.ini dest=/etc/php.d/xdebug.ini mode=0644
  sudo: yes
  notify:
    - reload httpd
  tags:
    - webserver
    - php
