---

- name: install apache and apache tools
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel
    - httpd-tools
  sudo: yes

- name: install php and modules
  yum: name={{ item }} state=present
  with_items:
    - php-5.3.3-27.el6_5.1
    - php-mysql
    - php-pecl-apc
    - php-cli
    - php-mbstring
    - php-gd
    - php-xml
    - php-pear
    - php-pecl-imagick
    - php-common
    - php-devel
    - php-imap
    - php-pdo
    - php-mcrypt
    - php-soap
  sudo: yes

- name: ensure apache is running
  service: name=httpd state=running enabled=yes
  sudo: yes

- name: configure docroot
  replace: dest=/etc/httpd/conf/httpd.conf regexp='^DocumentRoot.*' replace='DocumentRoot /vagrant_data'
  sudo: yes 

- name: add test vhost
  copy: src=omnique.com.conf dest=/etc/httpd/conf.d/omnique.com.conf mode=0644
  sudo: yes

- name: Add php.ini
  copy: src=php.ini dest=/etc/php.ini mode=0644
  sudo: yes
